'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ssip_form_ssip

    '''<summary>
    '''ToolkitScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ToolkitScriptManager1 As Global.AjaxControlToolkit.ToolkitScriptManager

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmdDraft1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDraft1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdRecv1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRecv1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdHRReview1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdHRReview1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mytabber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mytabber2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tabSendMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabSendMail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtto As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''cmdSendMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSendMail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcc As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtsubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsubject As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chk_sms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_sms As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtmessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmessage As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtidselect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidselect As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtidCCselect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidCCselect As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtidBCCSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidBCCSelect As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtidOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidOther As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''tabMailLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabMailLog As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GridAlertLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridAlertLog As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tabAttachFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabAttachFile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''FileUpload0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload0 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''cmdUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDeleteFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteFile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridFileAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridFileAttach As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''idp_log control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents idp_log As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GridviewIDPLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridviewIDPLog As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tabDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''panelDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelDetail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txttopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttopic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtdept_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdept_all As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cmdAddRelateDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddRelateDept As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdRemoveRelateDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRemoveRelateDept As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtdept_select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdept_select As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtperson_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtperson_all As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cmdAddRelatePerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddRelatePerson As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdRemoveRelatePerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRemoveRelatePerson As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtperson_select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtperson_select As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txts1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txts1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txts2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txts2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txts3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txts3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtdate_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate_status As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MaskedEditExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaskedEditExtender1 As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''txtdate_report_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate_report_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txts4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txts4 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsourcetype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsourcetype As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtsource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsource As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_suggest1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_suggest1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_suggest2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_suggest2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_suggest3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_suggest3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_suggest4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_suggest4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_suggest5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_suggest5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''UpdatePanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel6 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtBenefit_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBenefit_all As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cmdAddRelateBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddRelateBenefit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdRemoveRelateBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRemoveRelateBenefit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtBenefit_select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBenefit_select As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''GridSuggest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridSuggest As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtadd_problem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadd_problem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtadd_suggest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadd_suggest As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdAddTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddTopic As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDelTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDelTopic As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdOrderTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdOrderTopic As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridFile As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''FileUpload2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload2 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''Button11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button11 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDelFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDelFile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridBenefit As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtadd_benefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadd_benefit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdAddBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddBenefit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDelBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDelBenefit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdOrderBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdOrderBenefit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''chk_confirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_confirm As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''panelDetail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelDetail2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSSIPNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSIPNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSSIPEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSIPEmpName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSSIPempCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSIPempCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSSIPDeptName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSIPDeptName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSSIPTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSIPTopic As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSSIPRelateDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSIPRelateDept As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtSSIPRelatePerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSIPRelatePerson As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lblSSIPStatusName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSIPStatusName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSSIPFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSIPFrom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSSIPSuggest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSIPSuggest As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSSIPRelateBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSIPRelateBenefit As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''GridSuggest2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridSuggest2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridFile2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridFile2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridBenefit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridBenefit2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tabHR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabHR As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''panelHR1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelHR1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCommittee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCommittee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtdept_impl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdept_impl As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtawarddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtawarddate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblSumReward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumReward As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''panelHR2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelHR2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtSSIPResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSIPResult As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtdetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdetail As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtpublic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpublic As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtcommittee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcommittee As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtedittopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtedittopic As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtkeyword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtkeyword As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdescription As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txthr_alldept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthr_alldept As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cmdHRAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdHRAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdHrRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdHrRemove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txthr_selectdept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthr_selectdept As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txthr_alldept2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthr_alldept2 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cmdImplAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdImplAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdImplRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdImplRemove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txthr_impldept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthr_impldept As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtreward_sum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtreward_sum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtaward_scale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaward_scale As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''panel_reward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_reward As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblscale1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblscale1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblscale2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblscale2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblscale3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblscale3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblscale4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblscale4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbenefit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbenefit1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbenefit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbenefit2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbenefit3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbenefit3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbenefit4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbenefit4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblreward16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblreward16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbenefit_old control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbenefit_old As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtbenefit_new control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbenefit_new As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtbenefit_factor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbenefit_factor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtbenefit_final control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbenefit_final As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtamount_reward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtamount_reward As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegularExpressionValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator4 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''cmdCalulate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCalulate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblamount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblamount1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblamount2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblamount2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblamount3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblamount3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtssip_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtssip_category As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtonthespot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtonthespot As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RegularExpressionValidator6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator6 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtsrppoint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsrppoint As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtsrp_bonus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsrp_bonus As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegularExpressionValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator2 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtsrp_total_point control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsrp_total_point As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcash As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RegularExpressionValidator5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator5 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtaward_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaward_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MaskedEditExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaskedEditExtender2 As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''CalendarExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtreceive_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtreceive_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MaskedEditExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaskedEditExtender3 As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''CalendarExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender2 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''Image3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image3 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtb1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtb2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtb3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtb4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb4 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtb5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtb5 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc5 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc9 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc13 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc6 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc10 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc14 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc7 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc11 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc15 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc4 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc8 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc12 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtsc16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsc16 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscale1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscale1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtscale2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscale2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtscale3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscale3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtreward_remark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtreward_remark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tabDeptManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabDeptManager As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNumSup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumSup As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panelManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelManager1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GridComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridComment As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''linkDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkDept As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image6 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Image7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image7 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panelAddComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelAddComment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmdSaveDeptReview2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveDeptReview2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtadd_subject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadd_subject As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcomment_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcomment_detail As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''panelManagerReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelManagerReview As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtanswer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtanswer1 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtmgr_reason1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmgr_reason1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtanswer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtanswer2 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtmgr_reason2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmgr_reason2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtanswer3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtanswer3 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtmgr_reason3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmgr_reason3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtanswer4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtanswer4 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtmgr_reason4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmgr_reason4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtanswer5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtanswer5 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtmgr_reason5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmgr_reason5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtanswer51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtanswer51 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtmgr_reason51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmgr_reason51 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtbudget_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbudget_num As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RegularExpressionValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator3 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblDeptAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptAll As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cmdAddDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddDept As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdRemoveDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRemoveDept As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblDeptSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptSelect As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''chk_benefit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_benefit1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_benefit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_benefit2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtbenefit_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbenefit_num As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RegularExpressionValidator7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator7 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''chk_benefit3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_benefit3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_benefit4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_benefit4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_benefit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_benefit5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_benefit6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_benefit6 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtplan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtplan As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtother As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''cmdAddComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddComment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''tabCommittee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabCommittee As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNumCom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumCom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''panelCommittee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelCommittee As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''panel_intangible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_intangible As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GridCommittee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridCommittee As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblPersonSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPersonSum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIntangAward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIntangAward As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTangAward control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTangAward As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAwardAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAwardAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''linkCommittee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkCommittee As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Image5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''panelAddCommiteeComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelAddCommiteeComment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmdSaveReview2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveReview2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtcom_ans1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcom_ans1 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtcom_reason1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcom_reason1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcom_ans2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcom_ans2 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtcom_reason2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcom_reason2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtamount_old control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtamount_old As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtamount_new control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtamount_new As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtamount_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtamount_save As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdCal11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCal11 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtamount_cal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtamount_cal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtscorename1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscorename1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtscore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscore1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtscorename2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscorename2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtscore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscore2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtscorename3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscorename3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtscore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscore3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtscorename4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscorename4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtscore4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscore4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtscorename5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscorename5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtscore5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscore5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtadd_award_scale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadd_award_scale As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtsum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdCommitteComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCommitteComment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdCommitteComment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCommitteComment1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''tab_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tab_update As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNumComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumComment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridInformation As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtadd_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadd_update As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdAddUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''div_activity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_activity As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdNew As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridActivity As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblPersonNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPersonNum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHourNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHourNum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAverage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAverage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdDraft2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDraft2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdSubmit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSubmit2 As Global.System.Web.UI.WebControls.Button
End Class
