'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class idp_idp_topic_master

    '''<summary>
    '''div_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_status As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GridTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridTopic As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtadd_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadd_category As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtdept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdept As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtadd_topic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadd_topic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtadd_topic_en control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadd_topic_en As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdAddTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddTopic As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDelTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDelTopic As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdSaveOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveOrder As Global.System.Web.UI.WebControls.Button
End Class
