'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace cfb

    Partial Public Class cfb_cfb_service_recovery

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ScriptManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''panelDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents panelDetail As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblCFBcomment1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtfeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtfeedback As Global.System.Web.UI.HtmlControls.HtmlTextArea

        '''<summary>
        '''lblCFBcomment2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtsolution control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtsolution As Global.System.Web.UI.HtmlControls.HtmlTextArea

        '''<summary>
        '''lblCFBcomment3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''GridDept control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridDept As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''txtadd_dept control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtadd_dept As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''service control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents service As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblCFBcomment4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCFBcomment5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment5 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txts1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txts1 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblCFBcomment6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment6 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txts2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txts2 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblCFBcomment7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment7 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCFBcomment8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment8 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txts11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txts11 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblCFBcomment9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment9 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txts22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txts22 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblCFBcomment10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment10 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''complain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents complain As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblCFBcomment11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtcom1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtcom1 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblCFBcomment12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment12 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtcom2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtcom2 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblCFBcomment13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment13 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCFBcomment14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment14 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtcustomer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtcustomer As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtcus_detail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtcus_detail As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''lblCFBcomment19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment19 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chk_tel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_tel As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblCFBcomment20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment20 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txttel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txttel As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_email control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_email As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblCFBcomment21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment21 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtemail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtemail As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_othter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_othter As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblCFBcomment22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCFBcomment22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtother control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtother As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''cmdSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
