'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace cfb

    Partial Public Class cfb_home

        '''<summary>
        '''txtdate1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtdate1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtdate2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtdate2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtdept control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtdept As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtstatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtstatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtfindhn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtfindhn As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtcfbno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtcfbno As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtowner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtowner As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chk_showall control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_showall As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtfinddoctor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtfinddoctor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtspecialty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtspecialty As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtunit_defendant control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtunit_defendant As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''cmdReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdReset As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''chkFlag control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkFlag As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkChangeToDraft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkChangeToDraft As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkMoveToIR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkMoveToIR As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNum As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''div_dept_priority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents div_dept_priority As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtdept_priority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtdept_priority As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdExport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdExport As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''GridView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
