'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Game_MasterPage

    '''<summary>
    '''lblPathWay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPathWay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGroupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGroupName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtzone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtzone As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdAddIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddIP As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdIPDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdIPDel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIP As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txttarget_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttarget_all As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cmdAddTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddTarget As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdRemoveTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRemoveTarget As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txttarget_select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttarget_select As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtfind_jobtype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfind_jobtype As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdSearchJobType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSearchJobType As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblJobTypeAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJobTypeAll As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cmdAddType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddType As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdRemoveType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRemoveType As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblJobTypeSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJobTypeSelect As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''txtqty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtqty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtgroup_th control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtgroup_th As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtgroup_en control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtgroup_en As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''txtdetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdetail As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''cmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtempcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtempcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdClearScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdClearScore As Global.System.Web.UI.WebControls.Button
End Class
