'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace incident

    Partial Public Class incident_AnesControl

        '''<summary>
        '''chk_topic11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic11 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic12 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic13 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic14 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic15 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic16 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic21 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic22 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic23 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''topic2_other control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents topic2_other As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_topic31 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic31 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic32 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic32 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic33 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic33 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''topic3_other control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents topic3_other As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_topic41 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic41 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic42 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic42 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic43 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic43 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic44 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic44 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic45 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic45 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic46 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic46 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic47 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic47 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''topic4_other control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents topic4_other As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_topic51 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic51 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic52 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic52 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic53 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic53 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic54 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic54 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic55 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic55 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic56 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic56 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''topic5_other control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents topic5_other As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_topic61 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic61 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic62 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic62 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic63 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic63 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic64 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic64 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic65 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic65 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic66 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic66 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic67 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic67 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''topic6_other control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents topic6_other As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_topic71 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic71 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic72 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic72 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic73 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic73 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic74 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic74 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic75 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic75 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic76 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic76 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic77 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic77 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic78 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic78 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''topic7_other control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents topic7_other As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_topic81 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic81 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic82 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic82 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic83 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic83 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic84 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic84 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic85 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic85 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic86 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic86 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic87 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic87 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic88 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic88 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''topic8_other control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents topic8_other As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_topic91 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic91 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic92 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic92 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic93 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic93 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''topic9_other control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents topic9_other As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_topic101 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic101 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic102 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic102 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic103 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic103 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''topic10_other control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents topic10_other As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_topic111 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic111 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic112 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic112 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic113 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic113 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic114 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic114 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic115 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic115 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic116 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic116 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic117 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic117 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic121 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic121 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic122 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic122 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic123 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic123 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic124 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic124 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic125 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic125 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic131 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic131 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic132 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic132 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic133 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic133 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic134 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic134 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic135 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic135 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic136 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic136 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic137 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic137 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''topic13_other1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents topic13_other1 As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_topic138 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic138 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic139 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic139 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic1310 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic1310 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic1311 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic1311 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic1312 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic1312 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic1313 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic1313 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic1314 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic1314 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''topic13_other2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents topic13_other2 As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_topic141 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic141 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic142 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic142 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic143 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic143 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic144 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic144 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic151 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic151 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic152 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic152 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic153 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic153 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic161 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic161 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic162 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic162 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_topic163 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_topic163 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''comment1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents comment1 As Global.System.Web.UI.HtmlControls.HtmlTextArea

        '''<summary>
        '''comment2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents comment2 As Global.System.Web.UI.HtmlControls.HtmlTextArea

        '''<summary>
        '''comment3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents comment3 As Global.System.Web.UI.HtmlControls.HtmlTextArea

        '''<summary>
        '''comment4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents comment4 As Global.System.Web.UI.HtmlControls.HtmlTextArea

        '''<summary>
        '''comment5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents comment5 As Global.System.Web.UI.HtmlControls.HtmlTextArea

        '''<summary>
        '''comment6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents comment6 As Global.System.Web.UI.HtmlControls.HtmlTextArea
    End Class
End Namespace
