'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class incident_DeleteScanControl

    '''<summary>
    '''gridDeleteScan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridDeleteScan As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtwrong_hn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtwrong_hn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcorrect_hn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcorrect_hn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtwrong_doc_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtwrong_doc_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcorrect_doc_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcorrect_doc_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdate_report_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate_report_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCFBdetail9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBdetail9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthour As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmin As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtdate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdate_report_CalendarExtender0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate_report_CalendarExtender0 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblCFBdetail10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBdetail10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthour2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthour2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtmin2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtmin2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtwrong_doctor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtwrong_doctor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcorrect_doctor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcorrect_doctor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtwrong_doc_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtwrong_doc_no As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcorrect_doc_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcorrect_doc_no As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtwrong_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtwrong_other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcorrect_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcorrect_other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtscandel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscandel1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscandel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscandel2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscanunit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanunit1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscanunit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanunit2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscanunit3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanunit3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscanunit4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanunit4 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscanunit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanunit5 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscanunit_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanunit_other As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_typeofdoc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofdoc1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofdoc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofdoc2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofdoc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofdoc3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofdoc4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofdoc4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofdoc5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofdoc5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofdoc6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofdoc6 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofdoc7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofdoc7 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofdoc8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofdoc8 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofdoc9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofdoc9 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofptrec1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofptrec1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofptrec2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofptrec2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofptrec3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofptrec3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_typeofptrec4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_typeofptrec4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtscanedoc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanedoc1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscanedoc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanedoc2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtbarcode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbarcode1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtbarcode2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbarcode2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''chk_opddoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_opddoc As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_ipddoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_ipddoc As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_opddoc_n1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_opddoc_n1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_ipddoc_n1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_ipddoc_n1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_opddoc_n2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_opddoc_n2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_ipddoc_n2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_ipddoc_n2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_opddoc_n3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_opddoc_n3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_ipddoc_n3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_ipddoc_n3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_cardiacdoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_cardiacdoc As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_filmdoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_filmdoc As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_cardiacdoc_n1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_cardiacdoc_n1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_filmdoc_n1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_filmdoc_n1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_cardiacdoc_n2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_cardiacdoc_n2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_filmdoc_n2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_filmdoc_n2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_cardiacdoc_n3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_cardiacdoc_n3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_filmdoc_n3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_filmdoc_n3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_labdoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_labdoc As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_otherdoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_otherdoc As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_labdoc_n1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_labdoc_n1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_otherdoc_n1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_otherdoc_n1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_labdoc_n2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_labdoc_n2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_otherdoc_n2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_otherdoc_n2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_labdoc_n3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_labdoc_n3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_otherdoc_n3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_otherdoc_n3 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtscanerrorby1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanerrorby1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscanerrorby2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanerrorby2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscanerrorby3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanerrorby3 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscanerrorby4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanerrorby4 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscanerrorby_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscanerrorby_other As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_scancause_h1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_h7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h7 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_h2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_h8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h8 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_h3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_h9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h9 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_h4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_h10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h10 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_h5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_h11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h11 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_h6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h6 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_h12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_h12 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtscancause_hother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscancause_hother As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_scancause_p1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_p1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_p6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_p6 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_p2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_p2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_p7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_p7 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_p3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_p3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_p8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_p8 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_p4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_p4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_p9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_p9 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_p5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_p5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_p10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_p10 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtscancause_pother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscancause_pother As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_scancause_c1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_c1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_c4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_c4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_c2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_c2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_c5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_c5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtscancause_cother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscancause_cother As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_scancause_c3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_c3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_s1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_s1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_s4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_s4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_s2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_s2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_s5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_s5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_s3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_s3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_scancause_s6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_s6 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtscancause_sother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscancause_sother As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_scancause_m1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_m1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtscancausem1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscancausem1 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''chk_scancause_m2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_scancause_m2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtscancausem2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscancausem2 As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtscancorrect1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscancorrect1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtscancorrect2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtscancorrect2 As Global.System.Web.UI.WebControls.RadioButton
End Class
