'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace incident

    Partial Public Class incident_MedControl

        '''<summary>
        '''lblIRMed1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIRMed1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblIRMed2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIRMed2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chk_wrongtime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrongtime As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrongroute control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrongroute As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrongdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrongdate As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrongrate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrongrate As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_omission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_omission As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wronglabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wronglabel As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrongform control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrongform As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrongbrand control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrongbrand As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrongdose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrongdose As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_extradose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_extradose As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrongiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrongiv As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrong_deteriorate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrong_deteriorate As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrong_prep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrong_prep As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrong_drugerror control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrong_drugerror As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrong_duplicate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrong_duplicate As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrong_formular control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrong_formular As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrong_qty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrong_qty As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrong_drug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrong_drug As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_wrong_pt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_wrong_pt As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_allergy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_allergy As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtmed_level control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtmed_level As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtmed_category control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtmed_category As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''GridDrugWrongName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridDrugWrongName As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''txtdruggroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtdruggroup As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtdrugname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtdrugname As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''txtlasa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtlasa As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkHighAlert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHighAlert As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkFloorStock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkFloorStock As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkSmartPump control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSmartPump As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkBCMA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkBCMA As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdAddWrongName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddWrongName As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtdrugname_right control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtdrugname_right As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''Image2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''chk_err_order control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_err_order As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_err_transcription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_err_transcription As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_err_key control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_err_key As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_err_verify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_err_verify As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_err_predis control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_err_predis As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_err_dispensing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_err_dispensing As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_err_preadmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_err_preadmin As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_err_admin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_err_admin As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_err_monitor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_err_monitor As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_order_type1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_order_type1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_order_type2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_order_type2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_order_type3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_order_type3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_order_type4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_order_type4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_order_type5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_order_type5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_order_type6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_order_type6 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_order_type7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_order_type7 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtorder_type control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtorder_type As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtrobot1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtrobot1 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''txtrobot2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtrobot2 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''txtcpoe1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtcpoe1 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''txtcpoe2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtcpoe2 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''txtmar1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtmar1 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''txtmar2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtmar2 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''txtmed_period control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtmed_period As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtmed_hour1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtmed_hour1 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtmed_min1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtmed_min1 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chk_rn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_rn As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtrn_exp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtrn_exp As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chk_ph control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_ph As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtph_exp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtph_exp As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chk_aph control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_aph As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtaph_exp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtaph_exp As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''GridMedPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridMedPeriod As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''txtadd_jobtype control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtadd_jobtype As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtadd_period control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtadd_period As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtworkprocess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtworkprocess As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdAddPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddPeriod As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''chk_h1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_h1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_h2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_h2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_h3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_h3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_h4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_h4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_h5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_h5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_h6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_h6 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_h7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_h7 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_h8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_h8 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_h9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_h9 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_h10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_h10 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_h11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_h11 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txth11_remark control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txth11_remark As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_c1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_c1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_c2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_c2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_c3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_c3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_c4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_c4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_c5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_c5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_c6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_c6 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_c7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_c7 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_c8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_c8 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtc8_remark control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtc8_remark As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_p1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p6 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p7 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p8 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p9 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p10 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p11 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p12 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p13 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p14 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p15 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p16 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p17 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p18 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p19 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p20 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_p21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_p21 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtp21_remark control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtp21_remark As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_s1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_s1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_s2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_s2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_s3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_s3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_s4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_s4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_s5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_s5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_s6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_s6 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_s7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_s7 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_s8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_s8 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_s9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_s9 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txts9_remark control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txts9_remark As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_d1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_d1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_d2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_d2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_d3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_d3 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_d4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_d4 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_d5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_d5 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''chk_d6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_d6 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtd6_remark control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtd6_remark As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_m1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_m1 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtm1_remark control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtm1_remark As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chk_m2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chk_m2 As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtm2_remark control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtm2_remark As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtfloor1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtfloor1 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''txtfloor2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtfloor2 As Global.System.Web.UI.WebControls.RadioButton
    End Class
End Namespace
