'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class incident_rtpPhebControl

    '''<summary>
    '''lblinfiltration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinfiltration As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblinfiltrationsymptom1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinfiltrationsymptom1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblinfiltrationsymptom2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinfiltrationsymptom2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblphlebitis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblphlebitis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblphlebitissymptom1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblphlebitissymptom1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblphlebitissymptom2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblphlebitissymptom2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblphlebitissymptom3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblphlebitissymptom3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblphlebitissymptom4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblphlebitissymptom4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblphlebitissymptom5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblphlebitissymptom5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblphlebitissymptom6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblphlebitissymptom6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblphlebitissymptom7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblphlebitissymptom7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltypeofphlebitis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltypeofphlebitis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblguageno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblguageno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblivsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblivsite As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblivfluid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblivfluid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblivmed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblivmed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcatherter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcatherter As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblmedhx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmedhx As Global.System.Web.UI.WebControls.Label
End Class
