'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class incident_rptPressureControl

    '''<summary>
    '''lbltypeofpressure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltypeofpressure As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblstageofpressure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstageofpressure As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpressurelocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpressurelocation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpressuredocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpressuredocument As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpressureprevention1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpressureprevention1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpressureprevention2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpressureprevention2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpressureintrinsic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpressureintrinsic As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpressureextrinsic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpressureextrinsic As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpressuredevice1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpressuredevice1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblpressuredevice2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpressuredevice2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbradenscale1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbradenscale1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbradenscale2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbradenscale2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbradenscale3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbradenscale3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbradenscale4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbradenscale4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbradenscale5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbradenscale5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblbradenscale6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbradenscale6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScore As Global.System.Web.UI.WebControls.Label
End Class
