'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class star_preview_star

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''panelDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelDetail As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblStarNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStarNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCFBdetail10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBdetail10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtname_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtname_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_hn_remark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_hn_remark As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCFBdetail11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBdetail11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtcomplain_remark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcomplain_remark As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_profile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_profile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCFBdetail4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBdetail4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCFBdetail5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBdetail5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtcountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcountry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIRdetail23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRdetail23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtptage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtptage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIRdetail5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRdetail5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIRdetail24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRdetail24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtptsex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtptsex As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCFBdetail12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBdetail12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtfeedback_from control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfeedback_from As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_source_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_source_other As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCFBdetail13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBdetail13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtfeedback_remark11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfeedback_remark11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_cfb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_cfb As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCFBNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCFBNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCFBcomment14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBcomment14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtcustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcustomer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_response_remark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_response_remark As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtcus_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcus_detail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCFBcomment19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBcomment19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_response_method control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_response_method As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCFBcomment20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBcomment20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txttel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCFBcomment21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBcomment21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtemail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCFBcomment22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBcomment22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtother control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtother As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtstar_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstar_detail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''section1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents section1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCFBdetail3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBdetail3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txttitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttitle As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtptname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtptname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lblIRdetail20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRdetail20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtlocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlocation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIRdetail21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRdetail21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtroom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtroom As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIRdetail14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRdetail14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtservicetype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtservicetype As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIRdetail9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRdetail9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtsegment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsegment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCFBdetail8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCFBdetail8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtdate_report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate_report As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIRdetail22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRdetail22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtdate_complaint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate_complaint As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtnominee_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnominee_type As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNominee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNominee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeptSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptSelect As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDocSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocSelect As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtcustom_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcustom_name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridManagerComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridManagerComment As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''GridComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridComment As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblSumEndorse1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumEndorse1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEndorseDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEndorseDetail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumNotEndorse1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumNotEndorse1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthr_recog_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthr_recog_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtevent_admire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtevent_admire As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtsentence_admire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsentence_admire As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txthr_detail_combo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthr_detail_combo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chk_communicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_communicate As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_relative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_relative As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_talent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_talent As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chk_quality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_quality As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txthr_recog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthr_recog As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthr_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthr_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txthr_commit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthr_commit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtstar_comment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstar_comment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtsrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsrp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtcash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcash As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtdate_award control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate_award As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtdate_receive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate_receive As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtstar_remark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstar_remark As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMainTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMainTopic As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubTopic As Global.System.Web.UI.WebControls.Label
End Class
