'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class star_star_message

    '''<summary>
    '''lblInnovation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInnovation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridNews As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtbiMonthDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbiMonthDept As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''GripStarTopSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GripStarTopSubmit As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtbiMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbiMonth As Global.System.Web.UI.WebControls.DropDownList
End Class
